version: "3"
services:
  transactions:
    image: bernicezerafa11/transactions:latest
    depends_on:
      - mysql
    ports:
      - "8542:8080"
    environment:
      - DATABASE_HOST=192.168.99.100 # change to mysql if running without docker-machine
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=transfers
      - DATABASE_PORT=13306 # change to 3306 if running without docker-machine
  bankaccounts:
    image: bernicezerafa11/bankaccounts:latest
    depends_on:
      - mysql
    ports:
      - "8209:8080"
    environment:
      - DATABASE_HOST=192.168.99.100 # change to mysql if running without docker-machine
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=bankaccounts
      - DATABASE_PORT=13306 # change to 3306 if running without docker-machine
  mysql:
    image: mysql:5.7
    ports:
      - "13306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
